// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhKdQNLE97A0QvvHL2POuGMJqqZ1lnIRQ',
    appId: '1:578799157681:web:9426c09c10b1adcc4abd90',
    messagingSenderId: '578799157681',
    projectId: 'donor-darah-bc2cb',
    authDomain: 'donor-darah-bc2cb.firebaseapp.com',
    storageBucket: 'donor-darah-bc2cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0gjdudFMn9ykzjtZ9-s0iVE4blY_hnw',
    appId: '1:578799157681:android:60959723147d13994abd90',
    messagingSenderId: '578799157681',
    projectId: 'donor-darah-bc2cb',
    storageBucket: 'donor-darah-bc2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA81sFZeqHnRBXtxQkPBowfL-LHwhX3FwU',
    appId: '1:578799157681:ios:1cda3b74429639584abd90',
    messagingSenderId: '578799157681',
    projectId: 'donor-darah-bc2cb',
    storageBucket: 'donor-darah-bc2cb.appspot.com',
    iosClientId: '578799157681-sh9i62niipekaegog6ktjj6qlok99ss8.apps.googleusercontent.com',
    iosBundleId: 'com.example.donorDarah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA81sFZeqHnRBXtxQkPBowfL-LHwhX3FwU',
    appId: '1:578799157681:ios:1cda3b74429639584abd90',
    messagingSenderId: '578799157681',
    projectId: 'donor-darah-bc2cb',
    storageBucket: 'donor-darah-bc2cb.appspot.com',
    iosClientId: '578799157681-sh9i62niipekaegog6ktjj6qlok99ss8.apps.googleusercontent.com',
    iosBundleId: 'com.example.donorDarah',
  );
}
